# Generated by Django 4.1.1 on 2023-08-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Registerdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Log_id', models.CharField(max_length=30)),
                ('User_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.logindata')),
            ],
        ),
    ]
