# Generated by Django 4.1.1 on 2023-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0004_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Location',
            field=models.CharField(max_length=30),
        ),
    ]
