# Generated by Django 4.1.1 on 2023-09-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0007_registerdata_modelfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdata',
            old_name='modelfile',
            new_name='Image',
        ),
    ]
