# Generated by Django 4.1.1 on 2023-09-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0008_rename_modelfile_registerdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
