# Generated by Django 4.1.1 on 2023-09-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0006_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdata',
            name='modelfile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
