# Generated by Django 4.1.1 on 2023-09-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0009_contactus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
